export const GET_MOVIES = "GET_MOVIES";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SEARCH_MOVIES_GENRE = "SEARCH_MOVIES_GENRE";
export const SEARCH_MOVIES_DIRECTOR = "SEARCH_MOVIES_DIRECTOR";
export const SEARCH_MOVIES_ACTOR = "SEARCH_MOVIES_ACTOR";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const SORT_MOVIES_BY_SCORE = "SORT_MOVIES_BY_SCORE";
export const FILTER_MOVIES_BY_YEAR = "FILTER_MOVIES_BY_YEAR";
export const FILTER_MOVIES_BY_RATING = "FILTER_MOVIES_BY_RATING";

export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";

export const SET_LOADING = "SET_LOADING";
export const MOVIES_ERROR = "MOVIES_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const ERROR = "ERROR";
export const LOGOUT = "LOGOUT";
export const SET_USER = "SET_USER";
export const NOT_VERIFIED = "NOT_VERIFIED";
export const VERIFY = "VERIFY";
export const VERIFY_ERROR = "VERIFY_ERROR";

export const REGISTER = "REGISTER";
export const NAME_TAKEN = "NAME_TAKEN";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const NO_MATCH = "NO_MATCH";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_ERROR = "CHANGE_ERROR";

export const GET_QUESTION = "GET_QUESTION";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const QUESTION_ERROR = "QUESTION_ERROR";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";

export const POST_REVIEW = "POST_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const GET_REVIEWS = "GET_REVIEWS";
export const EDIT_REVIEW = "EDIT_REVIEW";

export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";

export const GET_PROFILE_REVIEWS = "GET_PROFILE_REVIEWS";
export const GET_WISHLIST = "GET_WISHLIST";
export const WISHLIST_ERROR = "WISHLIST_ERROR";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const WISHLIST_CHECK = "WISHLIST_CHECK";
export const PUBLIC_USER = "PUBLIC_USER";

export const GET_BANNED_LIST = "GET_BANNED_LIST";
export const BAN_USER = "BAN_USER";
export const BANNED_LIST_ERROR = "BANNED_LIST_ERROR";
export const BANNED = "BANNED";

export const GET_USER_BY_ID = "GET_USER_BY_ID";

export const UNEXPECTED_ERROR = "UNEXPECTED_ERROR";

export const ADMIN_CHECK = "ADMIN_CHECK";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const DELETE_USER = "DELETE_USER";
export const RESET_REDIR = "RESET_REDIR";

export const ADD_ACTOR = "ADD_ACTOR";
export const REMOVE_ACTOR = "REMOVE_ACTOR";
export const RESET_ACTORS = "RESET_ACTORS";

export const GET_FRIENDS = "GET_FRIENDS";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const ADD_PARTNER = "ADD_PARTNER";
export const REMOVE_PARTNER = "REMOVE_PARTNER";
export const CHECK_PARTNER = "CHECK_PARTNER";
export const GET_COMPATABILITY = "GET_COMPATABILITY";
